name: Submit

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: yarn install

      - name: Build the archive
        run: yarn build:package

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: latest
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v1
        env:
          PUPPETEER_EXECUTABLE_PATH: /opt/hostedtoolcache/chromium/latest/x64/chrome
        with:
          artifact: "web-ext-artifacts/copy_guard-{version}.zip"
          keys: ${{ secrets.SUBMIT_KEYS }}
